@Library('my-lib')_
import com.shlib.pipeline
node(){
    
stage("cloning the code1"){
    checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], gitTool: 'Default', submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/csenapati12/maven-samples.git']]])
    echo "clone1"
}
 
    stage('sh-maven1'){
        p1 = new pipeline()
        p1.build()   
    }
stage("packaging1"){
   sh '''set JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_144
    mvn package'''
    echo "packaging"
}
stage("Deployment1"){
    sh '''cd C:\\chaitanya\\devops\\training\\july-batch
cmd /k deploy.bat'''

    echo "Deployment"
}
    
}
