
node(){
    
stage("cloning the code1"){
    checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], gitTool: 'Default', submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/csenapati12/maven-samples.git']]])
    echo "clone1"
}
 stage("Dir"){
     sh "ls"
     echo "Dir"
}
   
    
}
